format = """
$username\
$localip\
$directory\
"""

right_format = """
$sudo\
${custom.is_git}\
${custom.git_saround_start}\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
${custom.git_saround_end}\
$rust\
${custom.starship_time}
${custom.stow_repo}
"""

add_newline = false
continuation_prompt = "[∙](bright-black) "
palette = "prop"

[palettes.prop]
purple = "#745196"
bright_red = "#f90206"
red = "#aa494b"
green = "#1abc70"
git_red = "#F26F4E"
blue = "#1a68bc"

[sudo]
# symbol = " "
symbol = " "
disabled = false
format = "[$symbol]($style)"
style = "bold bright_red"

[time]
disabled = false
time_format = "%a%b%d %H:%M"
format = "[$time]($style)"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = ""
style = "bold git_red"
ignore_branches = [ "master", "main" ]

[git_state]
format = "[state( progress_current/progress_total)](style)"

[git_commit]
format = "[hashtag](style)"

[git_status]
format = "([$all_status$ahead_behind]($style))"

[git_metrics]
disabled = false

[rust]
format = "[$symbol](red)[($version )]($style)"
symbol = '󱘗 '
style = "bold yellow"

[localip]
disabled = false 
format = "[$localipv4]($style) "
ssh_only = true 
style = "yellow bold"

[username]
# disabled = false
format = "[$user]($style) "
show_always = true 
style_root = "red bold"
style_user = "yellow bold"

[directory]
format = "[$read_only]($read_only_style)[$path]($style) "
truncate_to_repo = true
read_only = " "
truncation_symbol = "󱞽 "
style = "cyan bold"

# displays git logo if you are in a git repo
[custom.is_git]
description = "Currently in a git repo"
command = "echo '󰊢'"
when = "git status"
style = "git_red"

[custom.git_saround_start]
description = "a wrapper for all the git info"
format = "[$symbol($output)]($style)"
command = "echo '{'"
when = "starship_git_status.sh"
style = "git_red"

[custom.git_saround_end]
description = "a wrapper for all the git info"
format = "[$symbol($output)]($style) "
command = "echo '}'"
when = "starship_git_status.sh"
style = "git_red"

[custom.starship_time]
format = "$output"
description = "my custom time command"
command = "prop-time aoc"
when = true
style = ""

[custom.stow_repo]
format = " [$symbol](git_red)"
symbol = ""
when = "starship_git_status.sh"
